export const LOGIN_ACTION = {
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
  SET_SET_PASSWORD: "SET_SET_PASSWORD",
  SET_USER_DETAILS: "SET_USER_DETAILS",
};
