export const LOGIN_REDUCER = {
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
  SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGOUT: "LOGOUT",
};

export const USER_REDUCER = {
  USER_REQUEST: "USER_REQUEST",
  SET_USER_LIST: "SET_USER_LIST",
};
