export const LOGIN_REDUCER = {
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
  SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGOUT: "LOGOUT",
};

export const USER_REDUCER = {
  USER_REQUEST: "USER_REQUEST",
  SET_USER_LIST: "SET_USER_LIST",
  SET_NAME: "SET_NAME",
  SET_JOB: "SET_JOB",
  SET_NAME_ERROR: "SET_NAME_ERROR",
  SET_JOB_ERROR: "SET_JOB_ERROR",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  GET_USER_DETAIL: "GET_USER_DETAIL",
  SET_USER_DETAIL: "SET_USER_DETAIL",
  UPDATE_USER_DETAIL: "UPDATE_USER_DETAIL",
  SET_EMAIL: "SET_EMAIL",
  SET_FIRST_NAME: "SET_FIRST_NAME",
  SET_LAST_NAME: "SET_LAST_NAME",
};
